# (1) Numpy VS python 

In [503]:
l = range(1000000) # range returns list
l

range(0, 1000000)

In [16]:
import numpy as np


In [504]:
d = np.arange(1000000) # arange returns array
d

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [18]:
%time for i in range(1,10): r = [x*2 for x in l] # for list 

Wall time: 2.18 s


In [19]:
%time for i in range(1,10): r=d*2 # for array 

Wall time: 116 ms


# (2) nd array 

In [20]:
import numpy as np

In [21]:
np.zeros((4,4)) # 4 x 4 array putting is zero 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((4,4)) # 4 x 4 array having ones as data 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.empty((5,5)) # for random data array

array([[2.37663529e-312, 2.58883487e-312, 2.41907520e-312,
        2.44029516e-312, 8.48798317e-313],
       [9.33678148e-313, 8.70018275e-313, 6.79038653e-313,
        6.79038653e-313, 6.79038653e-313],
       [6.79038654e-313, 6.79038653e-313, 2.41907520e-312,
        2.05833592e-312, 6.79038654e-313],
       [2.48273508e-312, 2.46151512e-312, 2.33419537e-312,
        6.79038654e-313, 2.44029516e-312],
       [2.58883487e-312, 2.41907520e-312, 6.79038654e-313,
        2.22522596e-306, 2.10077583e-312]])

In [24]:
l = [ 1,2,3,4] # list

In [25]:
np.array(l) # list can be converted into an array.

array([1, 2, 3, 4])

In [26]:
x = np.arange(1,100,10) # it gives an array with the diffrence of 10 
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [27]:
x.shape  # size of dimention 

(10,)

In [510]:
x = np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [515]:
x.shape

(10, 10)

In [516]:
x.dtype  # for data type we use dtype 

dtype('float64')

In [517]:
x.reshape((25,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
x.ndim

1

# Arthimetic with ndarray

In [33]:
a = np.random.randn((10)) # random data 

In [34]:
b = np.random.randn((10))  # random data

In [35]:
a + b   

array([ 1.27397395,  0.02370387, -1.35566474,  0.50100686,  0.7709244 ,
       -1.41504432, -1.08568121,  0.475274  ,  1.14141929, -1.35697576])

In [36]:
a - b

array([-0.75309232, -0.77630122, -0.733473  , -0.14974751, -2.9059735 ,
        0.56619177, -0.77711046, -0.34527809, -3.85137729, -0.49505155])

In [37]:
2*a

array([ 0.52088163, -0.75259735, -2.08913774,  0.35125935, -2.1350491 ,
       -0.84885255, -1.86279166,  0.12999591, -2.709958  , -1.85202731])

In [38]:
10*b

array([10.13533139,  4.00002549, -3.11095873,  3.25377185, 18.38448953,
       -9.90618042, -1.54285375,  4.10276042, 24.96398288, -4.30962109])

In [39]:
b*100000

array([101353.31386884,  40000.25485316, -31109.58726308,  32537.71845134,
       183844.89533023, -99061.80424214, -15428.53754443,  41027.6041577 ,
       249639.82883201, -43096.21089854])

In [40]:
a

array([ 0.26044081, -0.37629867, -1.04456887,  0.17562968, -1.06752455,
       -0.42442627, -0.93139583,  0.06499796, -1.354979  , -0.92601365])

In [41]:
b

array([ 1.01353314,  0.40000255, -0.31109587,  0.32537718,  1.83844895,
       -0.99061804, -0.15428538,  0.41027604,  2.49639829, -0.43096211])

In [42]:
a>b

array([False, False, False, False, False,  True, False, False, False,
       False])

In [43]:
a[a>b] # for picking 

array([-0.42442627])

In [44]:
a[a<0]

array([-0.37629867, -1.04456887, -1.06752455, -0.42442627, -0.93139583,
       -1.354979  , -0.92601365])

# indexing and slicing 

In [45]:
import numpy as np

In [46]:
x = np.array([1,2,3,4,5])

In [47]:
x[x>2] # slicing 

array([3, 4, 5])

In [48]:
x[1:4]

array([2, 3, 4])

In [49]:
x =np.random.randn(5,2)

In [50]:
x

array([[-0.24615568,  1.00273683],
       [ 0.70014321, -0.18821665],
       [-1.91467283, -0.57043836],
       [ 2.09061744,  0.17747368],
       [-1.54553411, -1.98695874]])

In [51]:
x[0]

array([-0.24615568,  1.00273683])

In [52]:
x[0,1]

1.0027368346628038

In [53]:
x[x>0] # possitive data

array([1.00273683, 0.70014321, 2.09061744, 0.17747368])

In [54]:
x[x<0] # negative data

array([-0.24615568, -0.18821665, -1.91467283, -0.57043836, -1.54553411,
       -1.98695874])

In [55]:
x

array([[-0.24615568,  1.00273683],
       [ 0.70014321, -0.18821665],
       [-1.91467283, -0.57043836],
       [ 2.09061744,  0.17747368],
       [-1.54553411, -1.98695874]])

In [56]:
x[1:4,] = 0

In [57]:
x[0] = x[-1]

In [58]:
x[0] = 1

In [59]:
x

array([[ 1.        ,  1.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-1.54553411, -1.98695874]])

In [60]:
x[-1] = 1

In [61]:
x

array([[1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.]])

In [62]:
x = np.ones((5,5))

In [63]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
x[1:-1,1:-1] = 0

In [65]:
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
x>0

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True, False, False, False,  True],
       [ True,  True,  True,  True,  True]])

In [67]:
x


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
x[1:-1,1:-1]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Functions 


In [80]:
import numpy as np 

In [83]:
x = np.array([4,9,16,36,11]) # simple an array 

In [84]:
np.sqrt(x) 

array([2.        , 3.        , 4.        , 6.        , 3.31662479])

In [87]:
np.power(x,2)

array([  16,   81,  256, 1296,  121], dtype=int32)

In [92]:
x = np.array([4,9,16,36,11])
y = np.sqrt(x)
z = np.power(x,2)


In [93]:
x

array([ 4,  9, 16, 36, 11])

In [94]:
y

array([2.        , 3.        , 4.        , 6.        , 3.31662479])

In [95]:
z

array([  16,   81,  256, 1296,  121], dtype=int32)

In [96]:
l = x+y+z
np.array((l))

array([  22.        ,   93.        ,  276.        , 1338.        ,
        135.31662479])

In [103]:
p = np.sqrt(z)

In [105]:
 x == p

array([ True,  True,  True,  True,  True])

In [115]:
x

array([ 4,  9, 16, 36, 11])

In [119]:
x.max()

36

In [120]:
np.power(x,3)

array([   64,   729,  4096, 46656,  1331], dtype=int32)

In [122]:
np.sqrt(x)

array([2.        , 3.        , 4.        , 6.        , 3.31662479])

In [140]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
np.max(x)

9

In [141]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [142]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [143]:
np.power(x,4)

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561],
      dtype=int32)

In [148]:
np.shape(x)

(10,)

In [149]:
np.ndim(x)

1

In [150]:
x.ndim

1

In [155]:
x.dtype

dtype('int32')

# np.where



In [173]:
import numpy as np 

In [179]:
salary = np.array([-1,0,10000,240000])
salary

array([    -1,      0,  10000, 240000])

In [183]:
np.where(salary<0,"WTF","fine") #np.where(condition, true , false)

array(['WTF', 'fine', 'fine', 'fine'], dtype='<U4')

In [186]:
import numpy as np
x = np.zeros((10,10))
x[x==0] = 1
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [188]:
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [191]:
np.where(x==1,"T","F")

array([['T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T'],
       ['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'T'],
       ['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'T'],
       ['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'T'],
       ['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'T'],
       ['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'T'],
       ['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'T'],
       ['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'T'],
       ['T', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'F', 'T'],
       ['T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T', 'T']], dtype='<U1')

In [218]:
a = np.arange(0,10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [219]:
b = np.arange(0,20).reshape(2,10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [220]:
rows = np.concatenate((a,b),axis=1)
rows

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [217]:
rows

array([[ 0,  1,  2,  3,  4,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

# Mathematical and statistical 

In [247]:
import numpy as np

In [255]:
x = np.array([10,9,8,7,9,2])
x

array([10,  9,  8,  7,  9,  2])

In [256]:
x.mean()

7.5

In [269]:
x.cumsum()  # commulative sum

array([10, 19, 27, 34, 43, 45], dtype=int32)

In [270]:
x.cumprod()

array([   10,    90,   720,  5040, 45360, 90720], dtype=int32)

In [271]:
y = x>7
y

array([ True,  True,  True, False,  True, False])

In [272]:
y.sum()

4

In [273]:
y.any()

True

In [274]:
y.all()

False

In [275]:
x

array([10,  9,  8,  7,  9,  2])

In [279]:
x.sort()
x

array([ 2,  7,  8,  9,  9, 10])

In [280]:
np.unique(x) # unique will  be removed the same item from the array

array([ 2,  7,  8,  9, 10])

# File input and output

In [282]:
""" 
np.save(filename.npy,array)
np.load(filename.npy)
np.savez(filename.npz,array1,array2) 

"""

' \nnp.save(filename.npy,array)\nnp.load(filename.npy)\nnp.savez(filename.npz,array1,array2) \n\n'

In [283]:
import numpy as np

In [285]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [293]:
np.save("text1",a)

In [301]:
 loading_file = np.load("text1.npy")

In [302]:
loading_file

array([1, 2, 3, 4, 5, 6])

In [309]:
x = [1,2,3,4,5]   # one array
y = [9,8,7,6,5]    # second array
load_files = np.savez("files",x,y)  # saves two array
np.load("files.npz")   # we use "Z" in savez and extension 

# Linear Algebra Functions

In [336]:
import numpy as np

In [404]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [407]:
y = np.ones((2,3))
y

array([[1., 1., 1.],
       [1., 1., 1.]])

In [412]:
x.dot(y)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [349]:
z = x-y
z


array([[-1., -1.],
       [-1., -1.],
       [-1., -1.]])

In [347]:
z.transpose()

array([[-1., -1., -1.],
       [-1., -1., -1.]])

In [350]:
z.trace()

-2.0

In [353]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [354]:
x[1:-1,1:-1] = 2

In [376]:
z= x
z[1:-1,1:-1]=0
z

array([[3., 3., 3., 3., 1.],
       [3., 0., 0., 0., 1.],
       [3., 0., 0., 0., 1.],
       [3., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [377]:
x[0:4,0:4]=3
y= x
y

array([[3., 3., 3., 3., 1.],
       [3., 3., 3., 3., 1.],
       [3., 3., 3., 3., 1.],
       [3., 3., 3., 3., 1.],
       [1., 1., 1., 1., 1.]])

In [378]:
z.dot(y)

array([[37., 37., 37., 37., 13.],
       [37., 37., 37., 37., 13.],
       [37., 37., 37., 37., 13.],
       [37., 37., 37., 37., 13.],
       [13., 13., 13., 13.,  5.]])

# Pseudo Random Number




In [385]:
import numpy as np 

In [395]:
np.random.seed(10) # top value of the random numbers

In [447]:
y = np.random.normal(size=(3,3))
y
np.save("array",y)

In [402]:
y<11

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# NumPy Advanced Array Manipulations


# Reshape

In [413]:
import numpy as np

In [420]:
x = np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [422]:
x[1:-1,1:-1]=4
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 4., 4., 4., 4., 4., 4., 4., 4., 1.],
       [1., 4., 4., 4., 4., 4., 4., 4., 4., 1.],
       [1., 4., 4., 4., 4., 4., 4., 4., 4., 1.],
       [1., 4., 4., 4., 4., 4., 4., 4., 4., 1.],
       [1., 4., 4., 4., 4., 4., 4., 4., 4., 1.],
       [1., 4., 4., 4., 4., 4., 4., 4., 4., 1.],
       [1., 4., 4., 4., 4., 4., 4., 4., 4., 1.],
       [1., 4., 4., 4., 4., 4., 4., 4., 4., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [444]:
y = x.reshape((5,5,2,2)) # here we convert it into 4 dimensions 
y 


array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 1.]]],


       [[[1., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 1.],
         [1., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 1.]]],


       [[[1., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 1.],
         [1., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 1.]]],


       [[[1., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 1.],
         [1., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 1.]]],


       [[[1., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1.,

In [445]:
y.reshape(5,5,2,-1)

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 1.]]],


       [[[1., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 1.],
         [1., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 1.]]],


       [[[1., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 1.],
         [1., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 1.]]],


       [[[1., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 1.],
         [1., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 1.]]],


       [[[1., 4.],
         [4., 4.]],

        [[4., 4.],
         [4., 4.]],

        [[4., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1.,

In [449]:
y.ravel()  # convert into one dimenson 

array([ 1.484537  , -1.07980489, -1.97772828, -1.7433723 ,  0.26607016,
        2.38496733,  1.12369125,  1.67262221,  0.09914922])

In [451]:
y.flatten() # convert into one dimension 

array([ 1.484537  , -1.07980489, -1.97772828, -1.7433723 ,  0.26607016,
        2.38496733,  1.12369125,  1.67262221,  0.09914922])

# Concatenate


In [452]:
""""
[vstack]          axis = 0      # concatenate row wise 
[hstack]            axis = 1    # coloumn wise 
"""

'"\n[vstack]          axis = 0      # concatenate row wise \n[hstack]            axis = 1    # coloumn wise \n'

In [455]:
x=[[1,2,3],[4,5,6]]
x

[[1, 2, 3], [4, 5, 6]]

In [456]:
y = [[7,8,9],[10,11,12]]
y

[[7, 8, 9], [10, 11, 12]]

In [460]:
arr1 = np.array(x)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [461]:
arr2 = np.array(y)
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [462]:
np.concatenate((arr1,arr2),axis=0) # axis= 0 concatenate rows wise 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [463]:
np.concatenate((arr1,arr2),axis=1)  # axis = 1 concatenate coloumn wise 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [464]:
np.vstack((arr1,arr2)) # vstack,axis = 0, horizontal 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [467]:
np.hstack((arr1,arr2)) # hstack , axis = 1, coloumn

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

# Split

In [468]:
import numpy as np

In [479]:
x = [[1,2,3,4,5,6,7,8,9],
     [11,12,13,14,15,16,17,18,19]]
x

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [11, 12, 13, 14, 15, 16, 17, 18, 19]]

In [480]:
d = np.array(x)
d

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [485]:
np.split(d,[5,8],axis = 1) # split

[array([[ 1,  2,  3,  4,  5],
        [11, 12, 13, 14, 15]]), array([[ 6,  7,  8],
        [16, 17, 18]]), array([[ 9],
        [19]])]

In [489]:
np.hsplit(d,[8,5]) # axis = 1

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [11, 12, 13, 14, 15, 16, 17, 18]]),
 array([], shape=(2, 0), dtype=int32),
 array([[ 6,  7,  8,  9],
        [16, 17, 18, 19]])]

In [490]:
np.vsplit(d,[8,5])  # axis = 0 

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
        [11, 12, 13, 14, 15, 16, 17, 18, 19]]),
 array([], shape=(0, 9), dtype=int32),
 array([], shape=(0, 9), dtype=int32)]

# Tile & Repeat


In [499]:
import numpy as np 

In [500]:
d = np.array([1,5,7,8])

In [501]:
np.repeat(d,2) # repeat any number one by one horizontally

array([1, 1, 5, 5, 7, 7, 8, 8])

In [502]:
np.tile(d,2) # repeat in a bunch 

array([1, 5, 7, 8, 1, 5, 7, 8])